spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTHORIZATION-AUTHENTICATION
          predicates:
            - Path=/api/user/**
        - id: expense-server
          uri: lb://INCOMEEXPENSE
          predicates:
            - Path=/api/transactions/**
          filters:
            - AuthenticationPreFilter
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8080"
              - "http://localhost:8081"
            allowedMethods:
              - GET
              - POST
            allowedHeaders:
              - Content-Type
              - responseType
              - Authorization
            allowCredentials: true
server:
  port: 4000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    preferIpAddress: true

gateway:
  excludedUrl: /api/user, /login
keyStore:
  path: keystore.jks
  password: password
  alias: auth-server
